# Generated by Django 4.1.7 on 2023-04-12 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='item',
        ),
    ]
