# Generated by Django 4.1.7 on 2023-04-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_delete_persona_rename_nombre_producto_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('legajo', models.IntegerField(max_length=7)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
